#!/bin/bash
pushd coreos
vagrant up
# Vagrant can't set docker containers to autostart in CoreOS yet, so manually reprovision...
vagrant provision docker-registry
# Set the config value to an initial value
vagrant ssh core-01 --command "etcdctl set /restreference/swaggerBasePath http://172.17.8.101:8080"
ssh-add ~/.vagrant.d/insecure_private_key
popd
